# pipelines/predict_pipeline.py
import pandas as pd
import numpy as np
import os
import warnings # To show warnings clearly

# --- Imports from our modules ---
# Import ALL model classes that have a .load method
from models.ml_models.poisson_model import PoissonModel
from models.ml_models.random_forest_model import RandomForestModel
from models.ml_models.gradient_boosting_model import GradientBoostingModel
from models.ml_models.monte_carlo_model import MonteCarloModel

from models.utils.predict import format_predictions
from models.utils.features import BaseFeatureConfig # Keep for defaults

# --- Placeholder for PredictionConfig if not defined ---
# Remove this if you have a proper config file
class PredictionConfig:
    n_top_predictions = 7
    min_probability_threshold = 0.55
    required_match_info_cols = ['MatchID', 'HomeTeam', 'AwayTeam', 'Date'] # Example
    # Add flags for dual outcomes if needed by format_predictions
    include_1x2_ou25_duals = True
    include_dc_ou25_duals = True
    include_1x2_btts_duals = True
    include_dc_btts_duals = True
    include_ou25_btts_duals = True
    # Add flags for other duals generated by MonteCarloModel if format_predictions uses them
    # e.g., include_1x2_ou15_duals = True


# --- Model Loading Registry (Updated) ---
# Assumes models have a 'load' classmethod defined in BaseModel
MODEL_LOADERS = {
    "poisson": PoissonModel.load,
    "random_forest": RandomForestModel.load,
    "gradient_boosting": GradientBoostingModel.load,
    "monte_carlo": MonteCarloModel.load,
    # Add other models here as you create them
}


def run_prediction(model_path: str, new_data_path: str, output_path: str, model_type: str):
    """
    Loads a SINGLE trained model, predicts on new data, formats predictions,
    merges actual results if available, and saves the results.
    This function remains useful for evaluating individual models.
    """
    print(f"\n--- Starting Single Model Prediction Pipeline ---")
    print(f"Model path: {model_path}")
    print(f"New data path: {new_data_path}")
    print(f"Output path: {output_path}")
    print(f"Model type: {model_type}")

    # --- 1. Load Prediction Configuration ---
    try:
        pred_cfg = PredictionConfig() # Load prediction settings
        feature_cfg_defaults = BaseFeatureConfig()
        target_cols = feature_cfg_defaults.all_target_cols
        match_id_col = feature_cfg_defaults.match_id_col

        print(f"Using PredictionConfig: Top N={pred_cfg.n_top_predictions}, Threshold={pred_cfg.min_probability_threshold}")
        # Check which dual categories are included based on the lists in the config
        included_dual_types = []
        if pred_cfg.include_1x2_ou25_duals: included_dual_types.append("1X2 & O/U 2.5") 
        if pred_cfg.include_dc_ou25_duals: included_dual_types.append("Double Chance & O/U 2.5")
        if pred_cfg.include_1x2_btts_duals: included_dual_types.append("1X2 & BTTS")
        if pred_cfg.include_dc_btts_duals: included_dual_types.append("Double Chance & BTTS") 
        if pred_cfg.include_ou25_btts_duals: included_dual_types.append("O/U 2.5 & BTTS")
        print(f"Including Dual Outcome Types (calculated via scoreline): {', '.join(included_dual_types) if included_dual_types else 'None'}")
    except Exception as e:
        print(f"Error loading PredictionConfig or FeatureConfig defaults: {e}")
        raise

    # --- 2. Load Trained Model ---
    print(f"Loading trained model from: {model_path}")
    load_func = MODEL_LOADERS.get(model_type) # Use the updated registry
    assert load_func is not None, f"No loader found for model type '{model_type}' in MODEL_LOADERS."

    try:
        model = load_func(model_path)
        assert hasattr(model, 'predict_proba') and callable(model.predict_proba), f"Loaded model lacks 'predict_proba'."
        assert hasattr(model, 'features_in_') and model.features_in_, f"Loaded model lacks 'features_in_'."
        print(f"Model loaded successfully. Type: {type(model).__name__}, Trained on {len(model.features_in_)} features.")
    except FileNotFoundError:
        print(f"CRITICAL ERROR: Model file not found at {model_path}")
        raise
    except Exception as e:
        print(f"CRITICAL ERROR loading model '{model_type}' from {model_path}: {e}")
        raise

    # --- 3. Load New Processed Data ---
    print(f"Loading new data from: {new_data_path}")
    try:
        new_df_raw = pd.read_parquet(new_data_path, engine='pyarrow')
    except FileNotFoundError:
        print(f"CRITICAL ERROR: New data file not found at {new_data_path}")
        raise
    except Exception as e:
        print(f"CRITICAL ERROR loading new data parquet file: {e}")
        raise

    print(f"Loaded raw new data shape: {new_df_raw.shape}")
    if new_df_raw.empty:
        print("Warning: New data DataFrame is empty. No predictions will be generated.")
        # Create empty output file with correct columns and exit gracefully
        output_dir = os.path.dirname(output_path)
        if output_dir: os.makedirs(output_dir, exist_ok=True)
        # Include potential target columns in the empty output for consistency
        empty_cols = pred_cfg.required_match_info_cols + ["Rank", "Outcome", "Probability"] + target_cols
        pd.DataFrame(columns=empty_cols).to_csv(output_path, index=False)
        print(f"Empty prediction file created at {output_path}")
        print(f"--- Prediction Pipeline Complete (No Data) ---")
        return # Stop processing

    # Handle Duplicate MatchIDs
    if match_id_col not in new_df_raw.columns:
         raise KeyError(f"CRITICAL ERROR: Expected MatchID column '{match_id_col}' not found in the loaded data for deduplication.")

    initial_rows = len(new_df_raw)
    new_df = new_df_raw.drop_duplicates(subset=[match_id_col], keep='first').copy()
    dropped_rows = initial_rows - len(new_df)

    if dropped_rows > 0:
        warnings.warn(f"WARNING: Found and removed {dropped_rows} duplicate rows based on '{match_id_col}'. Kept the first occurrence for each MatchID.")
        print(f"Data shape after deduplication: {new_df.shape}")
    else:
        print("No duplicate MatchIDs found in the new data.")

    # Extract Actual Results if Available
    actual_results_df = None
    if set(target_cols).issubset(new_df.columns):
        print(f"Found actual result columns ({target_cols}) in the input data. Extracting for merging.")
        # Add date_col to the columns extracted for the actual_results_df
        actual_results_df = new_df[[match_id_col, feature_cfg_defaults.date_col] + target_cols].copy()
    else:
        missing_targets = set(target_cols) - set(new_df.columns)
        print(f"Warning: Actual result columns ({missing_targets}) not found in the input data. Cannot merge actual results.")

    # --- 4. Prepare Features (X) and Match Info ---
    print("Preparing features (X) and match info...")

    # Validate required features are present in the new data
    trained_features = model.features_in_
    actual_features = new_df.columns
    missing_features = set(trained_features) - set(actual_features)
    assert not missing_features, f"CRITICAL ERROR: New data is missing features the model was trained on: {missing_features}"

    # Identify extra columns, carefully excluding targets now
    known_info_cols = set(pred_cfg.required_match_info_cols) | set(target_cols)
    extra_features = set(actual_features) - set(trained_features) - known_info_cols
    if extra_features:
        print(f"Warning: New data has extra columns not used by the model or for info/targets: {extra_features}")

    # Select features in the exact order the model expects
    try:
        X_new = new_df[trained_features].copy()
    except KeyError as e:
         print(f"CRITICAL ERROR: Could not select all required features from new data. Missing: {e}")
         raise

    # Check for NaNs in features before prediction
    if X_new.isnull().any().any():
        nan_cols = X_new.columns[X_new.isnull().any()].tolist()
        warnings.warn(f"WARNING: Features (X_new) for prediction contain NaNs in columns: {nan_cols}. Predictions may be unreliable or fail. Ensure data is processed correctly.")
        # Depending on model tolerance, you might raise an error here:
        # assert not X_new.isnull().any().any(), "Features (X_new) for prediction contain NaNs."

    # Extract Match Info using columns defined in PredictionConfig
    required_info_cols = set(pred_cfg.required_match_info_cols)
    missing_info_cols = required_info_cols - set(new_df.columns)
    assert not missing_info_cols, f"CRITICAL ERROR: New data is missing required match info columns defined in PredictionConfig: {missing_info_cols}"

    match_info = new_df[pred_cfg.required_match_info_cols].copy()

    assert X_new.shape[0] == match_info.shape[0], "CRITICAL ERROR: Mismatch between feature rows and match info rows."
    print(f"Prepared X_new shape: {X_new.shape}")


    # --- 5. Generate Base Probabilities (from the single loaded model) ---
    print(f"Generating base probabilities using {model_type} model...")
    try:
        base_probabilities = model.predict_proba(X_new) # Calls predict_proba of the loaded model
        assert isinstance(base_probabilities, dict), "model.predict_proba() did not return a dictionary."
        print(f"Generated {len(base_probabilities)} probability keys.")
    except Exception as e:
        print(f"CRITICAL ERROR during model prediction: {e}")
        raise

    # --- 6. Format Predictions ---
    print("Formatting final predictions using PredictionConfig...")
    try:
        # Determine model prefix
        # Assuming model_type is "poisson", "random_forest", etc.
        current_model_prefix = f"{model_type}_"

        final_predictions = format_predictions(
            base_probabilities,
            match_info,
            pred_cfg,
            model_prefix=current_model_prefix # Pass the determined prefix
        )
        assert isinstance(final_predictions, pd.DataFrame), "'format_predictions' did not return a DataFrame."
    except Exception as e:
        print(f"CRITICAL ERROR during prediction formatting: {e}")
        raise

    # Merge Actual Results
    output_df = final_predictions
    if actual_results_df is not None:
        print(f"Merging actual results ({target_cols}) with predictions...")
        # Ensure MatchID types match before merge, if necessary (though usually string/object)
        try:
             output_df = pd.merge(
                final_predictions,
                actual_results_df,
                on=match_id_col,
                how='left' # Keep all predictions, add results where available
            )
             print("Merge successful.")
             # Basic validation after merge
             assert len(output_df) == len(final_predictions), "Merge changed the number of prediction rows."
             assert set(target_cols).issubset(output_df.columns), "Target columns are missing after merge."
        except Exception as e:
            warnings.warn(f"WARNING: Failed to merge actual results with predictions. Error: {e}. Saving predictions without results.")
            output_df = final_predictions # Fallback to predictions only

    # --- 7. Save Final Data ---
    print(f"Saving final output data to: {output_path}")
    try:
        output_dir = os.path.dirname(output_path)
        if output_dir:
            os.makedirs(output_dir, exist_ok=True)
        output_df.to_csv(output_path, index=False) # Save the (potentially merged) DataFrame
        print(f"Output saved successfully. Shape: {output_df.shape}")
        if not output_df.empty:
            print("Sample Output Data:")
            print(output_df.head())
        else:
            print("No predictions generated meeting criteria.")

    except Exception as e:
        print(f"CRITICAL ERROR saving output data to {output_path}: {e}")
        raise

    print(f"--- Single Model Prediction Pipeline Complete ---")


if __name__ == "__main__":
    # This block now needs to be adapted to loop through the models you want predictions for

    # --- Define Parameters ---
    BASE_PATH = '/Users/barroca888/Downloads/Agenticfc/AgenticFC888' # Adjust if needed
    DATA_OUTPUT_DIR = os.path.join(BASE_PATH, 'models', 'data', 'outputs')
    PREDICTIONS_DIR = os.path.join(DATA_OUTPUT_DIR, 'predictions', 'individual_models') # Save individual preds here
    os.makedirs(PREDICTIONS_DIR, exist_ok=True)

    # Define which models and odds settings to generate predictions for
    MODELS_TO_PREDICT = ["poisson", "random_forest", "gradient_boosting", "monte_carlo"]
    ODDS_SETTINGS = [
        {"suffix": "without_odds", "include_odds": False},
        {"suffix": "with_odds", "include_odds": True},
    ]

    for odds_setting in ODDS_SETTINGS:
        odds_suffix = odds_setting["suffix"]
        include_odds = odds_setting["include_odds"]
        print(f"\n>>> Generating predictions for setting: {odds_suffix.upper()} <<<")

        new_data_path = os.path.join(DATA_OUTPUT_DIR, f'processed_{odds_suffix}.parquet')
        if not os.path.exists(new_data_path):
            print(f"Skipping {odds_suffix}: Input data not found at {new_data_path}")
            continue

        for model_key in MODELS_TO_PREDICT:
            model_filename = f'{model_key}_{odds_suffix}_v1.joblib' # Matches train_pipeline output format
            model_path = os.path.join(DATA_OUTPUT_DIR, model_filename)
            output_filename = f'predictions_{model_key}_{odds_suffix}.csv'
            output_path = os.path.join(PREDICTIONS_DIR, output_filename)

            print(f"\n--- Predicting with: {model_filename} ---")
            if os.path.exists(model_path):
                try:
                    run_prediction( # Call the existing function for this single model
                        model_path=model_path,
                        new_data_path=new_data_path,
                        output_path=output_path,
                        model_type=model_key # Pass the correct type
                    )
                except Exception as e:
                    print(f"!!! Prediction failed for {model_filename}: {e} !!!")
                    import traceback
                    traceback.print_exc()
            else:
                print(f"Skipping prediction: Model file not found at {model_path}")