TEAMS = {
    # Premier League Teams (England)
    "Liverpool": "England",
    "Arsenal": "England",
    "Nottingham Forest": "England",
    "Chelsea": "England",
    "Manchester City": "England",
    "Newcastle": "England",
    "Brighton": "England",
    "Fulham": "England",
    "Aston Villa": "England",
    "Bournemouth": "England",
    "Brentford": "England",
    "Crystal Palace": "England",
    "Manchester Utd": "England",
    "Tottenham": "England",
    "Everton": "England",
    "West Ham": "England",
    "Wolves": "England",
    "Ipswich": "England",
    "Leicester": "England",
    "Southampton": "England",
    
    # Championship Teams (England)
    "Leeds": "England",
    "Burnley": "England",
    "Sheffield Utd": "England",
    "Sunderland": "England",
    "Coventry": "England",
    "West Brom": "England",
    "Bristol City": "England",
    "Middlesbrough": "England",
    "Blackburn": "England",
    "Watford": "England",
    "Millwall": "England",
    "Sheffield Wed": "England",
    "Norwich": "England",
    "Preston": "England",
    "QPR": "England",
    "Swansea": "England",
    "Portsmouth": "England",
    "Oxford United": "England",
    "Hull City": "England",
    "Stoke City": "England",
    "Cardiff": "England",
    "Derby": "England",
    "Luton": "England",
    "Plymouth": "England",
    
    # LaLiga Teams (Spain)
    "Barcelona": "Spain",
    "Real Madrid": "Spain",
    "Atletico Madrid": "Spain",
    "Athletic Club": "Spain",
    "Villarreal": "Spain",
    "Betis": "Spain",
    "Mallorca": "Spain",
    "Celta Vigo": "Spain",
    "Rayo Vallecano": "Spain",
    "Sevilla": "Spain",
    "Getafe": "Spain",
    "Real Sociedad": "Spain",
    "Girona": "Spain",
    "Osasuna": "Spain",
    "Espanyol": "Spain",
    "Valencia": "Spain",
    "Deportivo Alaves": "Spain",
    "Leganes": "Spain",
    "Las Palmas": "Spain",
    "Valladolid": "Spain",
    
    # Serie A Teams (Italy)
    "Inter": "Italy",
    "Napoli": "Italy",
    "Atalanta": "Italy",
    "Juventus": "Italy",
    "Lazio": "Italy",
    "Bologna": "Italy",
    "AC Milan": "Italy",
    "Roma": "Italy",
    "Fiorentina": "Italy",
    "Udinese": "Italy",
    "Torino": "Italy",
    "Genoa": "Italy",
    "Como": "Italy",
    "Verona": "Italy",
    "Cagliari": "Italy",
    "Lecce": "Italy",
    "Parma": "Italy",
    "Empoli": "Italy",
    "Unione Venezia": "Italy",
    "Monza": "Italy",
    
    # Bundesliga Teams (Germany)
    "Bayern Munich": "Germany",
    "Bayer Leverkusen": "Germany",
    "FSV Mainz 05": "Germany",
    "Eintracht Frankfurt": "Germany",
    "RB Leipzig": "Germany",
    "SC Freiburg": "Germany",
    "Borussia Monchengladbach": "Germany",
    "VfL Wolfsburg": "Germany",
    "FC Augsburg": "Germany",
    "VfB Stuttgart": "Germany",
    "Borussia Dortmund": "Germany",
    "Werder Bremen": "Germany",
    "Union Berlin": "Germany",
    "1899 Hoffenheim": "Germany",
    "FC St. Pauli": "Germany",
    "VfL Bochum": "Germany",
    "Holstein Kiel": "Germany",
    "FC Heidenheim": "Germany",
    
    # Ligue 1 Teams (France)
    "Paris Saint Germain": "France",
    "Marseille": "France",
    "Monaco": "France",
    "Nice": "France",
    "Lille": "France",
    "Lyon": "France",
    "Strasbourg": "France",
    "Lens": "France",
    "Stade Brestois 29": "France",
    "Toulouse": "France",
    "Auxerre": "France",
    "Rennes": "France",
    "Nantes": "France",
    "Angers": "France",
    "Reims": "France",
    "Le Havre": "France",
    "St Etienne": "France",
    "Montpellier": "France",
    
    # Liga Portugal Teams (Portugal)
    "Sporting CP": "Portugal",
    "Benfica": "Portugal",
    "FC Porto": "Portugal",
    "SC Braga": "Portugal",
    "Santa Clara": "Portugal",
    "Guimaraes": "Portugal",
    "Casa Pia": "Portugal",
    "Estoril": "Portugal",
    "Famalicao": "Portugal",
    "Rio Ave": "Portugal",
    "Moreirense": "Portugal",
    "Arouca": "Portugal",
    "Nacional": "Portugal",
    "Gil Vicente": "Portugal",
    "Estrela Da Amadora": "Portugal",
    "Vilafranquense": "Portugal",
    "Farense": "Portugal",
    "Boavista": "Portugal",
    
    # Eredivisie Teams (Netherlands)
    "Ajax": "Netherlands",
    "PSV": "Netherlands",
    "Utrecht": "Netherlands",
    "Feyenoord": "Netherlands",
    "Twente": "Netherlands",
    "AZ Alkmaar": "Netherlands",
    "Go Ahead Eagles": "Netherlands",
    "Fortuna Sittard": "Netherlands",
    "Groningen": "Netherlands",
    "Heerenveen": "Netherlands",
    "NEC Nijmegen": "Netherlands",
    "NAC Breda": "Netherlands",
    "Heracles": "Netherlands",
    "PEC Zwolle": "Netherlands",
    "Sparta Rotterdam": "Netherlands",
    "Willem II": "Netherlands",
    "Waalwijk": "Netherlands",
    "Almere City FC": "Netherlands",
    
    # Belgium - First Division A (Belgium)
    "Genk": "Belgium",
    "Club Brugge": "Belgium",
    "Union St. Gilloise": "Belgium",
    "Anderlecht": "Belgium",
    "Antwerp": "Belgium",
    "Gent": "Belgium",
    "Standard Liege": "Belgium",
    "Charleroi": "Belgium",
    "KV Mechelen": "Belgium",
    "KVC Westerlo": "Belgium",
    "OH Leuven": "Belgium",
    "FC Dender": "Belgium",
    "Cercle Brugge": "Belgium",
    "St Truiden": "Belgium",
    "Kortrijk": "Belgium",
    "Beerschot Wilrijk": "Belgium",
    
    # Scotland - Premiership (Scotland)
    "Celtic": "Scotland",
    "Rangers": "Scotland",
    "Hibernian": "Scotland",
    "Aberdeen": "Scotland",
    "Dundee Utd": "Scotland",
    "Hearts": "Scotland",
    "Motherwell": "Scotland",
    "St Mirren": "Scotland",
    "Ross County": "Scotland",
    "Kilmarnock": "Scotland",
    "Dundee": "Scotland",
    "St Johnstone": "Scotland",
    
    # Turkey - Super Lig (Turkey)
    "Galatasaray": "Turkey",
    "Fenerbahce": "Turkey",
    "Samsunspor": "Turkey",
    "Besiktas": "Turkey",
    "Eyupspor": "Turkey",
    "Gaziantep FK": "Turkey",
    "Goztepe": "Turkey",
    "Istanbul Basaksehir": "Turkey",
    "Trabzonspor": "Turkey",
    "Kasimpasa": "Turkey",
    "Rizespor": "Turkey",
    "Antalyaspor": "Turkey",
    "Konyaspor": "Turkey",
    "Alanyaspor": "Turkey",
    "BB Bodrumspor": "Turkey",
    "Sivasspor": "Turkey",
    "Kayserispor": "Turkey",
    "Hatayspor": "Turkey",
    "Adana Demirspor": "Turkey",
    
    # Austria - Bundesliga (Austria)
    "Sturm Graz": "Austria",
    "Austria Vienna": "Austria",
    "Wolfsberger AC": "Austria",
    "Red Bull Salzburg": "Austria",
    "Lask Linz": "Austria",
    "Rapid Vienna": "Austria",
    "FC BW Linz": "Austria",
    "TSV Hartberg": "Austria",
    "Austria Klagenfurt": "Austria",
    "WSG Swarovski Tirol": "Austria",
    "Grazer AK": "Austria",
    "SCR Altach": "Austria",
    
    # Switzerland - Super League (Switzerland)
    "Servette FC": "Switzerland",
    "FC Basel 1893": "Switzerland",
    "FC Lugano": "Switzerland",
    "FC Luzern": "Switzerland",
    "BSC Young Boys": "Switzerland",
    "FC Zurich": "Switzerland",
    "FC Lausanne-Sport": "Switzerland",
    "FC St. Gallen": "Switzerland",
    "FC Sion": "Switzerland",
    "Yverdon-Sport FC": "Switzerland",
    "Grasshopper-Club": "Switzerland",
    "FC Winterthur": "Switzerland",
    
    # Denmark - Superligaen (Denmark)
    "FC Midtjylland": "Denmark",
    "FC Copenhagen": "Denmark",
    "AGF": "Denmark",
    "Randers FC": "Denmark",
    "FC Nordsjaelland": "Denmark",
    "Brondby": "Denmark",
    "Silkeborg": "Denmark",
    "Viborg": "Denmark",
    "Aalborg": "Denmark",
    "Lyngby": "Denmark",
    "SonderjyskE": "Denmark",
    "Vejle": "Denmark",
    
    # Ukraine - Premier League (Ukraine)
    "Dinamo Kiev": "Ukraine",
    "FC Oleksandriya": "Ukraine",
    "Shakhter Donetsk": "Ukraine",
    "Polissya Zhytomyr": "Ukraine",
    "Kryvbas Kryvyi Rih": "Ukraine",
    "Zarya Lugansk": "Ukraine",
    "Karpaty Lviv": "Ukraine",
    "Veres": "Ukraine",
    "Rukh Lviv": "Ukraine",
    "Cherkasi": "Ukraine",
    "Livyi Bereg": "Ukraine",
    "Vorskla Poltava": "Ukraine",
    "Kolos Kovalivka": "Ukraine",
    "Obolon-Brovar Kiev": "Ukraine",
    "Chernomorets Odessa": "Ukraine",
    "Ingulets Petrove": "Ukraine",
    
    # Czech Republic - 1. Liga (Czech Republic)
    "Slavia Praha": "Czech Republic",
    "Sparta Praha": "Czech Republic",
    "Viktoria Plzen": "Czech Republic",
    "Banik Ostrava": "Czech Republic",
    "FK Jablonec": "Czech Republic",
    "Sigma Olomouc": "Czech Republic",
    "Mlada Boleslav": "Czech Republic",
    "Slovan Liberec": "Czech Republic",
    "Bohemians 1905": "Czech Republic",
    "Hradec Kralove": "Czech Republic",
    "Teplice": "Czech Republic",
    "Karvina": "Czech Republic",
    "Slovacko": "Czech Republic",
    "Dukla Praha": "Czech Republic",
    "Pardubice": "Czech Republic",
    "Dynamo Ceske Budejovice": "Czech Republic",
    
    # Greece - Super League (Greece)
    "Olympiakos Piraeus": "Greece",
    "AEK Athens": "Greece",
    "Panathinaikos": "Greece",
    "PAOK": "Greece",
    "Aris Thessalonikis": "Greece",
    "OFI": "Greece",
    "Atromitos Athinon": "Greece",
    "Asteras Tripolis": "Greece",
    "Panaitolikos": "Greece",
    "Levadiakos": "Greece",
    "Panserraikos": "Greece",
    "Volos NPS": "Greece",
    "Kallithea": "Greece",
    "Lamia": "Greece",
    
    # Poland - Ekstraklasa (Poland)
    "Rakow Czestochowa": "Poland",
    "Jagiellonia": "Poland",
    "Lech Poznan": "Poland",
    "Pogon Szczecin": "Poland",
    "Legia Warszawa": "Poland",
    "Gornik Zabrze": "Poland",
    "Cracovia Krakow": "Poland",
    "Motor Lublin": "Poland",
    "GKS Katowice": "Poland",
    "Piast Gliwice": "Poland",
    "Korona Kielce": "Poland",
    "Radomiak Radom": "Poland",
    "Widzew Lodz": "Poland",
    "Puszcza Niepolomice": "Poland",
    "Stal Mielec": "Poland",
    "Zaglebie Lubin": "Poland",
    "Lechia Gdansk": "Poland",
    "Slask Wroclaw": "Poland",
    
    # Croatia - HNL (Croatia)
    "HNK Rijeka": "Croatia",
    "HNK Hajduk Split": "Croatia",
    "NK Dinamo Zagreb": "Croatia",
    "NK Varazdin": "Croatia",
    "NK Slaven Belupo": "Croatia",
    "NK Osijek": "Croatia",
    "NK Lokomotiva Zagreb": "Croatia",
    "Istra 1961": "Croatia",
    "HNK Gorica": "Croatia",
    "Sibenik": "Croatia",
    
    # Serbia - Super Liga (Serbia)
    "Crvena Zvezda": "Serbia",
    "FK Partizan": "Serbia",
    "Radnicki 1923": "Serbia",
    "OFK Beograd": "Serbia",
    "Mladost Lucani": "Serbia",
    "Vojvodina": "Serbia",
    "Novi Pazar": "Serbia",
    "TSC Backa Topola": "Serbia",
    "Cukaricki": "Serbia",
    "Zeleznicar Pancevo": "Serbia",
    "FK IMT Beograd": "Serbia",
    "Spartak Subotica": "Serbia",
    "Napredak": "Serbia",
    "Radnicki Nis": "Serbia",
    "Tekstilac Odzaci": "Serbia",
    "Jedinstvo Ub": "Serbia",
    
    # Cyprus - 1. Division (Cyprus)
    "Aris": "Cyprus",
    "Pafos FC": "Cyprus",
    "A. E. Kition Larnaca": "Cyprus",
    "Omonia": "Cyprus",
    "Apoel": "Cyprus",
    "Apollon Limassol": "Cyprus",
    "Anorthosis": "Cyprus",
    "Ethnikos Achnas": "Cyprus",
    "Baskent Y. Ankara": "Cyprus",
    "Karmiotissa Polemidion": "Cyprus",
    "Omonia Aradippou": "Cyprus",
    "E.N. Paralimniou": "Cyprus",
    "Nea Salamis": "Cyprus",
    "Omonoia 29m": "Cyprus",
    
    # Romania - SuperLiga (Romania)
    "CFR 1907 Cluj": "Romania",
    "FCSB": "Romania",
    "CS Universitatea Craiova": "Romania",
    "Universitatea Cluj": "Romania",
    "Dinamo Bucuresti": "Romania",
    "Rapid Bucuresti": "Romania",
    "AFC Hermannstadt": "Romania",
    "Sepsi OSK": "Romania",
    "Petrolul Ploiesti": "Romania",
    "UTA Arad": "Romania",
    "Farul Constanta": "Romania",
    "FC Botosani": "Romania",
    "Poli Iasi": "Romania",
    "Otelul Galati": "Romania",
    "Unirea 2004 Slobozia": "Romania",
    "Gloria Buzau": "Romania",
    
    # Hungary - NB I (Hungary)
    "Puskas Academy": "Hungary",
    "Ferencvarosi TC": "Hungary",
    "Paks": "Hungary",
    "MTK Budapest": "Hungary",
    "Diosgyori VTK": "Hungary",
    "Gyori Eto FC": "Hungary",
    "Ujpest": "Hungary",
    "MOL Fehervar FC": "Hungary",
    "Zalaegerszegi TE": "Hungary",
    "Nyiregyhaza": "Hungary",
    "Debreceni VSC": "Hungary",
    "Kecskemeti TE": "Hungary",
    
    # Spain - LaLiga2 (Spain)
    "Levante": "Spain",
    "Mirandes": "Spain",
    "Elche": "Spain",
    "Racing Santander": "Spain",
    "Huesca": "Spain",
    "Oviedo": "Spain",
    "Almeria": "Spain",
    "Granada CF": "Spain",
    "Cordoba": "Spain",
    "Burgos": "Spain",
    "Cadiz": "Spain",
    "Eibar": "Spain",
    "Albacete": "Spain",
    "Deportivo La Coruna": "Spain",
    "Malaga": "Spain",
    "Sporting Gijon": "Spain",
    "Castellon": "Spain",
    "Zaragoza": "Spain",
    "CD Eldense": "Spain",
    "Tenerife": "Spain",
    "Racing De Ferrol": "Spain",
    "Cartagena": "Spain",
    
    # Germany - 2. Bundesliga (Germany)
    "Hamburger SV": "Germany",
    "FC Koln": "Germany",
    "SC Paderborn 07": "Germany",
    "FC Kaiserslautern": "Germany",
    "FC Magdeburg": "Germany",
    "Hannover 96": "Germany",
    "Fortuna Dusseldorf": "Germany",
    "SV Elversberg": "Germany",
    "FC Nurnberg": "Germany",
    "Karlsruher SC": "Germany",
    "FC Schalke 04": "Germany",
    "SpVgg Greuther Furth": "Germany",
    "SV Darmstadt 98": "Germany",
    "Preussen Munster": "Germany",
    "Hertha Berlin": "Germany",
    "Eintracht Braunschweig": "Germany",
    "SSV Ulm 1846": "Germany",
    "Jahn Regensburg": "Germany",
    
    # France - Ligue 2 (France)
    "Lorient": "France",
    "Metz": "France",
    "Paris FC": "France",
    "Dunkerque": "France",
    "Guingamp": "France",
    "Laval": "France",
    "Annecy": "France",
    "Bastia": "France",
    "Grenoble Foot 38": "France",
    "Pau": "France",
    "Ajaccio": "France",
    "Estac Troyes": "France",
    "Amiens": "France",
    "Red Star": "France",
    "Rodez": "France",
    "Clermont Foot": "France",
    "Martigues": "France",
    "Caen": "France",
    
    # Portugal - Liga Portugal 2 (Portugal)
    "Tondela": "Portugal",
    "Vizela": "Portugal",
    "Chaves": "Portugal",
    "Penafiel": "Portugal",
    "Alverca": "Portugal",
    "Leiria": "Portugal",
    "Torreense": "Portugal",
    "Benfica B": "Portugal",
    "Feirense": "Portugal",
    "Academico Viseu": "Portugal",
    "Felgueiras": "Portugal",
    "Leixoes": "Portugal",
    "Portimonense": "Portugal",
    "Maritimo": "Portugal",
    "Pacos Ferreira": "Portugal",
    "FC Porto B": "Portugal",
    "Oliveirense": "Portugal",
    "Mafra": "Portugal",
    
    # Netherlands - Eerste Divisie (Netherlands)
    "Volendam": "Netherlands",
    "ADO Den Haag": "Netherlands",
    "Excelsior": "Netherlands",
    "Dordrecht": "Netherlands",
    "Cambuur": "Netherlands",
    "De Graafschap": "Netherlands",
    "Telstar": "Netherlands",
    "Emmen": "Netherlands",
    "Den Bosch": "Netherlands",
    "Roda": "Netherlands",
    "Helmond Sport": "Netherlands",
    "FC Eindhoven": "Netherlands",
    "Jong AZ": "Netherlands",
    "MVV": "Netherlands",
    "Jong Ajax": "Netherlands",
    "VVV Venlo": "Netherlands",
    "TOP Oss": "Netherlands",
    "Jong PSV": "Netherlands",
    "Jong Utrecht": "Netherlands",
    "Vitesse": "Netherlands",
    
    # Italy - Serie B (Italy)
    "Sassuolo": "Italy",
    "Pisa": "Italy",
    "Spezia": "Italy",
    "Cremonese": "Italy",
    "Catanzaro": "Italy",
    "Juve Stabia": "Italy",
    "Cesena": "Italy",
    "Bari": "Italy",
    "Palermo": "Italy",
    "Modena": "Italy",
    "Sudtirol": "Italy",
    "Frosinone": "Italy",
    "Cittadella": "Italy",
    "Carrarese": "Italy",
    "Reggiana": "Italy",
    "Brescia": "Italy",
    "Sampdoria": "Italy",
    "Mantova": "Italy",
    "Salernitana": "Italy",
    "Cosenza": "Italy",
}