TEAM_DATA = {
    # England Teams (England)
    "Liverpool": {"api_id": "40", "country": "England"},
    "Arsenal": {"api_id": "42", "country": "England"},
    "Nottingham Forest": {"api_id": "65", "country": "England"},
    "Chelsea": {"api_id": "49", "country": "England"},
    "Manchester City": {"api_id": "50", "country": "England"},
    "Newcastle": {"api_id": "34", "country": "England"},
    "Brighton": {"api_id": "51", "country": "England"},
    "Fulham": {"api_id": "36", "country": "England"},
    "Aston Villa": {"api_id": "66", "country": "England"},
    "Bournemouth": {"api_id": "35", "country": "England"},
    "Brentford": {"api_id": "55", "country": "England"},
    "Crystal Palace": {"api_id": "52", "country": "England"},
    "Manchester Utd": {"api_id": "33", "country": "England"},
    "Tottenham": {"api_id": "47", "country": "England"},
    "Everton": {"api_id": "45", "country": "England"},
    "West Ham": {"api_id": "48", "country": "England"},
    "Wolves": {"api_id": "39", "country": "England"},
    "Ipswich": {"api_id": "57", "country": "England"},
    "Leicester": {"api_id": "46", "country": "England"},
    "Southampton": {"api_id": "41", "country": "England"},
    "Leeds": {"api_id": "63", "country": "England"},
    "Burnley": {"api_id": "44", "country": "England"},
    "Sheffield Utd": {"api_id": "62", "country": "England"},
    "Sunderland": {"api_id": "746", "country": "England"},
    "Coventry": {"api_id": "1346", "country": "England"},
    "West Brom": {"api_id": "60", "country": "England"},
    "Bristol City": {"api_id": "56", "country": "England"},
    "Middlesbrough": {"api_id": "70", "country": "England"},
    "Blackburn": {"api_id": "67", "country": "England"},
    "Watford": {"api_id": "38", "country": "England"},
    "Millwall": {"api_id": "58", "country": "England"},
    "Sheffield Wed": {"api_id": "62", "country": "England"},
    "Norwich": {"api_id": "71", "country": "England"},
    "Preston": {"api_id": "59", "country": "England"},
    "QPR": {"api_id": "72", "country": "England"},
    "Swansea": {"api_id": "76", "country": "England"},
    "Portsmouth": {"api_id": "1355", "country": "England"},
    "Oxford United": {"api_id": "1338", "country": "England"},
    "Hull City": {"api_id": "64", "country": "England"},
    "Stoke City": {"api_id": "75", "country": "England"},
    "Cardiff": {"api_id": "43", "country": "England"},
    "Derby": {"api_id": "69", "country": "England"},
    "Luton": {"api_id": "1359", "country": "England"},
    "Plymouth": {"api_id": "1357", "country": "England"},

    # Spain Teams (Spain)
    "Barcelona": {"api_id": "529", "country": "Spain"},
    "Real Madrid": {"api_id": "541", "country": "Spain"},
    "Atletico Madrid": {"api_id": "530", "country": "Spain"},
    "Athletic Club": {"api_id": "531", "country": "Spain"},
    "Villarreal": {"api_id": "533", "country": "Spain"},
    "Betis": {"api_id": "543", "country": "Spain"},
    "Mallorca": {"api_id": "798", "country": "Spain"},
    "Celta Vigo": {"api_id": "538", "country": "Spain"},
    "Rayo Vallecano": {"api_id": "728", "country": "Spain"},
    "Sevilla": {"api_id": "536", "country": "Spain"},
    "Getafe": {"api_id": "546", "country": "Spain"},
    "Real Sociedad": {"api_id": "548", "country": "Spain"},
    "Girona": {"api_id": "547", "country": "Spain"},
    "Osasuna": {"api_id": "727", "country": "Spain"},
    "Espanyol": {"api_id": "540", "country": "Spain"},
    "Valencia": {"api_id": "532", "country": "Spain"},
    "Deportivo Alaves": {"api_id": "542", "country": "Spain"},
    "Leganes": {"api_id": "537", "country": "Spain"},
    "Las Palmas": {"api_id": "534", "country": "Spain"},
    "Valladolid": {"api_id": "720", "country": "Spain"},
    "Levante": {"api_id": "539", "country": "Spain"},
    "Mirandes": {"api_id": "799", "country": "Spain"},
    "Elche": {"api_id": "797", "country": "Spain"},
    "Racing Santander": {"api_id": "4665", "country": "Spain"},
    "Huesca": {"api_id": "726", "country": "Spain"},
    "Oviedo": {"api_id": "718", "country": "Spain"},
    "Almeria": {"api_id": "723", "country": "Spain"},
    "Granada CF": {"api_id": "715", "country": "Spain"},
    "Cordoba": {"api_id": "713", "country": "Spain"},
    "Burgos": {"api_id": "9580", "country": "Spain"},
    "Cadiz": {"api_id": "724", "country": "Spain"},
    "Eibar": {"api_id": "545", "country": "Spain"},
    "Albacete": {"api_id": "722", "country": "Spain"},
    "Deportivo La Coruna": {"api_id": "544", "country": "Spain"},
    "Malaga": {"api_id": "535", "country": "Spain"},
    "Sporting Gijon": {"api_id": "731", "country": "Spain"},
    "Castellon": {"api_id": "5254", "country": "Spain"},
    "Zaragoza": {"api_id": "732", "country": "Spain"},
    "CD Eldense": {"api_id": "9692", "country": "Spain"},
    "Tenerife": {"api_id": "719", "country": "Spain"},
    "Racing De Ferrol": {"api_id": "9409", "country": "Spain"},
    "Cartagena": {"api_id": "5262", "country": "Spain"},

    # Italy Teams (Italy)
    "Inter": {"api_id": "505", "country": "Italy"},
    "Napoli": {"api_id": "492", "country": "Italy"},
    "Atalanta": {"api_id": "499", "country": "Italy"},
    "Juventus": {"api_id": "496", "country": "Italy"},
    "Lazio": {"api_id": "487", "country": "Italy"},
    "Bologna": {"api_id": "500", "country": "Italy"},
    "AC Milan": {"api_id": "489", "country": "Italy"},
    "Roma": {"api_id": "497", "country": "Italy"},
    "Fiorentina": {"api_id": "502", "country": "Italy"},
    "Udinese": {"api_id": "494", "country": "Italy"},
    "Torino": {"api_id": "503", "country": "Italy"},
    "Genoa": {"api_id": "495", "country": "Italy"},
    "Como": {"api_id": "895", "country": "Italy"},
    "Verona": {"api_id": "504", "country": "Italy"},
    "Cagliari": {"api_id": "490", "country": "Italy"},
    "Lecce": {"api_id": "867", "country": "Italy"},
    "Parma": {"api_id": "523", "country": "Italy"},
    "Empoli": {"api_id": "511", "country": "Italy"},
    "Unione Venezia": {"api_id": "517", "country": "Italy"},
    "Monza": {"api_id": "1579", "country": "Italy"},
    "Sassuolo": {"api_id": "488", "country": "Italy"},
    "Pisa": {"api_id": "801", "country": "Italy"},
    "Spezia": {"api_id": "515", "country": "Italy"},
    "Cremonese": {"api_id": "520", "country": "Italy"},
    "Catanzaro": {"api_id": "1687", "country": "Italy"},
    "Juve Stabia": {"api_id": "863", "country": "Italy"},
    "Cesena": {"api_id": "509", "country": "Italy"},
    "Bari": {"api_id": "508", "country": "Italy"},
    "Palermo": {"api_id": "522", "country": "Italy"},
    "Modena": {"api_id": "899", "country": "Italy"},
    "Sudtirol": {"api_id": "1578", "country": "Italy"},
    "Frosinone": {"api_id": "512", "country": "Italy"},
    "Cittadella": {"api_id": "510", "country": "Italy"},
    "Carrarese": {"api_id": "1581", "country": "Italy"},
    "Reggiana": {"api_id": "880", "country": "Italy"},
    "Brescia": {"api_id": "518", "country": "Italy"},
    "Sampdoria": {"api_id": "498", "country": "Italy"},
    "Mantova": {"api_id": "1693", "country": "Italy"},
    "Salernitana": {"api_id": "514", "country": "Italy"},
    "Cosenza": {"api_id": "10137", "country": "Italy"},

    # Germany Teams (Germany)
    "Bayern Munich": {"api_id": "157", "country": "Germany"},
    "Bayer Leverkusen": {"api_id": "168", "country": "Germany"},
    "FSV Mainz 05": {"api_id": "164", "country": "Germany"},
    "Eintracht Frankfurt": {"api_id": "169", "country": "Germany"},
    "RB Leipzig": {"api_id": "173", "country": "Germany"},
    "SC Freiburg": {"api_id": "160", "country": "Germany"},
    "Borussia Monchengladbach": {"api_id": "163", "country": "Germany"},
    "VfL Wolfsburg": {"api_id": "161", "country": "Germany"},
    "FC Augsburg": {"api_id": "170", "country": "Germany"},
    "VfB Stuttgart": {"api_id": "172", "country": "Germany"},
    "Borussia Dortmund": {"api_id": "165", "country": "Germany"},
    "Werder Bremen": {"api_id": "162", "country": "Germany"},
    "Union Berlin": {"api_id": "182", "country": "Germany"},
    "1899 Hoffenheim": {"api_id": "167", "country": "Germany"},
    "FC St. Pauli": {"api_id": "186", "country": "Germany"},
    "VfL Bochum": {"api_id": "176", "country": "Germany"},
    "Holstein Kiel": {"api_id": "191", "country": "Germany"},
    "FC Heidenheim": {"api_id": "180", "country": "Germany"},
    "Hamburger SV": {"api_id": "175", "country": "Germany"},
    "FC Koln": {"api_id": "192", "country": "Germany"},
    "SC Paderborn 07": {"api_id": "185", "country": "Germany"},
    "FC Kaiserslautern": {"api_id": "745", "country": "Germany"},
    "FC Magdeburg": {"api_id": "179", "country": "Germany"},
    "Hannover 96": {"api_id": "166", "country": "Germany"},
    "Fortuna Dusseldorf": {"api_id": "158", "country": "Germany"},
    "SV Elversberg": {"api_id": "1660", "country": "Germany"},
    "FC Nurnberg": {"api_id": "171", "country": "Germany"},
    "Karlsruher SC": {"api_id": "785", "country": "Germany"},
    "FC Schalke 04": {"api_id": "174", "country": "Germany"},
    "SpVgg Greuther Furth": {"api_id": "178", "country": "Germany"},
    "SV Darmstadt 98": {"api_id": "181", "country": "Germany"},
    "Preussen Munster": {"api_id": "1618", "country": "Germany"},
    "Hertha Berlin": {"api_id": "159", "country": "Germany"},
    "Eintracht Braunschweig": {"api_id": "744", "country": "Germany"},
    "SSV Ulm 1846": {"api_id": "1652", "country": "Germany"},
    "Jahn Regensburg": {"api_id": "177", "country": "Germany"},

    # France Teams (France)
    "Paris Saint Germain": {"api_id": "85", "country": "France"},
    "Marseille": {"api_id": "81", "country": "France"},
    "Monaco": {"api_id": "91", "country": "France"},
    "Nice": {"api_id": "84", "country": "France"},
    "Lille": {"api_id": "79", "country": "France"},
    "Lyon": {"api_id": "80", "country": "France"},
    "Strasbourg": {"api_id": "95", "country": "France"},
    "Lens": {"api_id": "116", "country": "France"},
    "Stade Brestois 29": {"api_id": "106", "country": "France"},
    "Toulouse": {"api_id": "96", "country": "France"},
    "Auxerre": {"api_id": "108", "country": "France"},
    "Rennes": {"api_id": "94", "country": "France"},
    "Nantes": {"api_id": "83", "country": "France"},
    "Angers": {"api_id": "77", "country": "France"},
    "Reims": {"api_id": "93", "country": "France"},
    "Le Havre": {"api_id": "111", "country": "France"},
    "St Etienne": {"api_id": "1063", "country": "France"},
    "Montpellier": {"api_id": "82", "country": "France"},
    "Lorient": {"api_id": "97", "country": "France"},
    "Metz": {"api_id": "112", "country": "France"},
    "Paris FC": {"api_id": "114", "country": "France"},
    "Dunkerque": {"api_id": "1304", "country": "France"},
    "Guingamp": {"api_id": "90", "country": "France"},
    "Laval": {"api_id": "433", "country": "France"},
    "Annecy": {"api_id": "3012", "country": "France"},
    "Bastia": {"api_id": "1305", "country": "France"},
    "Grenoble Foot 38": {"api_id": "101", "country": "France"},
    "Pau": {"api_id": "1297", "country": "France"},
    "Ajaccio": {"api_id": "98", "country": "France"},
    "Estac Troyes": {"api_id": "110", "country": "France"},
    "Amiens": {"api_id": "87", "country": "France"},
    "Red Star": {"api_id": "104", "country": "France"},
    "Rodez": {"api_id": "1301", "country": "France"},
    "Clermont Foot": {"api_id": "99", "country": "France"},
    "Martigues": {"api_id": "3200", "country": "France"},
    "Caen": {"api_id": "88", "country": "France"},

    # Portugal Teams (Portugal)
    "Sporting CP": {"api_id": "228", "country": "Portugal"},
    "Benfica": {"api_id": "211", "country": "Portugal"},
    "FC Porto": {"api_id": "212", "country": "Portugal"},
    "SC Braga": {"api_id": "217", "country": "Portugal"},
    "Santa Clara": {"api_id": "227", "country": "Portugal"},
    "Guimaraes": {"api_id": "224", "country": "Portugal"},
    "Casa Pia": {"api_id": "4716", "country": "Portugal"},
    "Estoril": {"api_id": "230", "country": "Portugal"},
    "Famalicao": {"api_id": "242", "country": "Portugal"},
    "Rio Ave": {"api_id": "226", "country": "Portugal"},
    "Moreirense": {"api_id": "215", "country": "Portugal"},
    "Arouca": {"api_id": "240", "country": "Portugal"},
    "Nacional": {"api_id": "225", "country": "Portugal"},
    "Gil Vicente": {"api_id": "762", "country": "Portugal"},
    "Estrela Da Amadora": {"api_id": "15130", "country": "Portugal"},
    "Vilafranquense": {"api_id": "220", "country": "Portugal"},
    "Farense": {"api_id": "231", "country": "Portugal"},
    "Boavista": {"api_id": "222", "country": "Portugal"},
    "Tondela": {"api_id": "218", "country": "Portugal"},
    "Vizela": {"api_id": "810", "country": "Portugal"},
    "Chaves": {"api_id": "223", "country": "Portugal"},
    "Penafiel": {"api_id": "235", "country": "Portugal"},
    "Alverca": {"api_id": "4724", "country": "Portugal"},
    "Leiria": {"api_id": "4662", "country": "Portugal"},
    "Torreense": {"api_id": "4799", "country": "Portugal"},
    "Benfica B": {"api_id": "211", "country": "Portugal"},
    "Feirense": {"api_id": "231", "country": "Portugal"},
    "Academico Viseu": {"api_id": "238", "country": "Portugal"},
    "Felgueiras": {"api_id": "4744", "country": "Portugal"},
    "Leixoes": {"api_id": "244", "country": "Portugal"},
    "Portimonense": {"api_id": "216", "country": "Portugal"},
    "Maritimo": {"api_id": "214", "country": "Portugal"},
    "Pacos Ferreira": {"api_id": "234", "country": "Portugal"},
    "FC Porto B": {"api_id": "212", "country": "Portugal"},
    "Oliveirense": {"api_id": "233", "country": "Portugal"},
    "Mafra": {"api_id": "245", "country": "Portugal"},

    # Netherlands Teams (Netherlands)
    "Ajax": {"api_id": "194", "country": "Netherlands"},
    "PSV": {"api_id": "197", "country": "Netherlands"},
    "Utrecht": {"api_id": "207", "country": "Netherlands"},
    "Feyenoord": {"api_id": "209", "country": "Netherlands"},
    "Twente": {"api_id": "415", "country": "Netherlands"},
    "AZ Alkmaar": {"api_id": "201", "country": "Netherlands"},
    "Go Ahead Eagles": {"api_id": "410", "country": "Netherlands"},
    "Fortuna Sittard": {"api_id": "205", "country": "Netherlands"},
    "Groningen": {"api_id": "202", "country": "Netherlands"},
    "Heerenveen": {"api_id": "210", "country": "Netherlands"},
    "NEC Nijmegen": {"api_id": "413", "country": "Netherlands"},
    "NAC Breda": {"api_id": "203", "country": "Netherlands"},
    "Heracles": {"api_id": "206", "country": "Netherlands"},
    "PEC Zwolle": {"api_id": "193", "country": "Netherlands"},
    "Sparta Rotterdam": {"api_id": "426", "country": "Netherlands"},
    "Willem II": {"api_id": "195", "country": "Netherlands"},
    "Waalwijk": {"api_id": "417", "country": "Netherlands"},
    "Almere City FC": {"api_id": "419", "country": "Netherlands"},
    "Volendam": {"api_id": "416", "country": "Netherlands"},
    "ADO Den Haag": {"api_id": "198", "country": "Netherlands"},
    "Excelsior": {"api_id": "196", "country": "Netherlands"},
    "Dordrecht": {"api_id": "409", "country": "Netherlands"},
    "Cambuur": {"api_id": "420", "country": "Netherlands"},
    "De Graafschap": {"api_id": "199", "country": "Netherlands"},
    "Telstar": {"api_id": "427", "country": "Netherlands"},
    "Emmen": {"api_id": "208", "country": "Netherlands"},
    "Den Bosch": {"api_id": "421", "country": "Netherlands"},
    "Roda": {"api_id": "414", "country": "Netherlands"},
    "Helmond Sport": {"api_id": "424", "country": "Netherlands"},
    "FC Eindhoven": {"api_id": "197", "country": "Netherlands"},
    "Jong AZ": {"api_id": "418", "country": "Netherlands"},
    "MVV": {"api_id": "412", "country": "Netherlands"},
    "Jong Ajax": {"api_id": "425", "country": "Netherlands"},
    "VVV Venlo": {"api_id": "204", "country": "Netherlands"},
    "TOP Oss": {"api_id": "423", "country": "Netherlands"},
    "Jong PSV": {"api_id": "411", "country": "Netherlands"},
    "Jong Utrecht": {"api_id": "428", "country": "Netherlands"},
    "Vitesse": {"api_id": "200", "country": "Netherlands"},

    # Belgium Teams (Belgium)
    "Genk": {"api_id": "742", "country": "Belgium"},
    "Club Brugge": {"api_id": "569", "country": "Belgium"},
    "Union St. Gilloise": {"api_id": "1393", "country": "Belgium"},
    "Anderlecht": {"api_id": "554", "country": "Belgium"},
    "Antwerp": {"api_id": "740", "country": "Belgium"},
    "Gent": {"api_id": "631", "country": "Belgium"},
    "Standard Liege": {"api_id": "733", "country": "Belgium"},
    "Charleroi": {"api_id": "736", "country": "Belgium"},
    "KV Mechelen": {"api_id": "266", "country": "Belgium"},
    "KVC Westerlo": {"api_id": "261", "country": "Belgium"},
    "OH Leuven": {"api_id": "260", "country": "Belgium"},
    "FC Dender": {"api_id": "6215", "country": "Belgium"},
    "Cercle Brugge": {"api_id": "741", "country": "Belgium"},
    "St Truiden": {"api_id": "735", "country": "Belgium"},
    "Kortrijk": {"api_id": "734", "country": "Belgium"},
    "Beerschot Wilrijk": {"api_id": "263", "country": "Belgium"},

    # Scotland Teams (Scotland)
    "Celtic": {"api_id": "247", "country": "Scotland"},
    "Rangers": {"api_id": "77", "country": "Scotland"},
    "Hibernian": {"api_id": "249", "country": "Scotland"},
    "Aberdeen": {"api_id": "252", "country": "Scotland"},
    "Dundee Utd": {"api_id": "1386", "country": "Scotland"},
    "Hearts": {"api_id": "254", "country": "Scotland"},
    "Motherwell": {"api_id": "256", "country": "Scotland"},
    "St Mirren": {"api_id": "251", "country": "Scotland"},
    "Ross County": {"api_id": "902", "country": "Scotland"},
    "Kilmarnock": {"api_id": "250", "country": "Scotland"},
    "Dundee": {"api_id": "253", "country": "Scotland"},
    "St Johnstone": {"api_id": "258", "country": "Scotland"},

    # Turkey Teams (Turkey)
    "Galatasaray": {"api_id": "645", "country": "Turkey"},
    "Fenerbahce": {"api_id": "611", "country": "Turkey"},
    "Samsunspor": {"api_id": "3603", "country": "Turkey"},
    "Besiktas": {"api_id": "549", "country": "Turkey"},
    "Eyupspor": {"api_id": "3588", "country": "Turkey"},
    "Gaziantep FK": {"api_id": "3573", "country": "Turkey"},
    "Goztepe": {"api_id": "994", "country": "Turkey"},
    "Istanbul Basaksehir": {"api_id": "564", "country": "Turkey"},
    "Trabzonspor": {"api_id": "998", "country": "Turkey"},
    "Kasimpasa": {"api_id": "1004", "country": "Turkey"},
    "Rizespor": {"api_id": "1007", "country": "Turkey"},
    "Antalyaspor": {"api_id": "1005", "country": "Turkey"},
    "Konyaspor": {"api_id": "607", "country": "Turkey"},
    "Alanyaspor": {"api_id": "996", "country": "Turkey"},
    "BB Bodrumspor": {"api_id": "3583", "country": "Turkey"},
    "Sivasspor": {"api_id": "1002", "country": "Turkey"},
    "Kayserispor": {"api_id": "1001", "country": "Turkey"},
    "Hatayspor": {"api_id": "3575", "country": "Turkey"},
    "Adana Demirspor": {"api_id": "3563", "country": "Turkey"},

    # Austria Teams (Austria)
    "Sturm Graz": {"api_id": "637", "country": "Austria"},
    "Austria Vienna": {"api_id": "601", "country": "Austria"},
    "Wolfsberger AC": {"api_id": "1025", "country": "Austria"},
    "Red Bull Salzburg": {"api_id": "571", "country": "Austria"},
    "Lask Linz": {"api_id": "1026", "country": "Austria"},
    "Rapid Vienna": {"api_id": "781", "country": "Austria"},
    "FC BW Linz": {"api_id": "1394", "country": "Austria"},
    "TSV Hartberg": {"api_id": "1072", "country": "Austria"},
    "Austria Klagenfurt": {"api_id": "1405", "country": "Austria"},
    "WSG Swarovski Tirol": {"api_id": "1398", "country": "Austria"},
    "Grazer AK": {"api_id": "4256", "country": "Austria"},
    "SCR Altach": {"api_id": "618", "country": "Austria"},

    # Switzerland Teams (Switzerland)
    "Servette FC": {"api_id": "2184", "country": "Switzerland"},
    "FC Basel 1893": {"api_id": "551", "country": "Switzerland"},
    "FC Lugano": {"api_id": "606", "country": "Switzerland"},
    "FC Luzern": {"api_id": "644", "country": "Switzerland"},
    "BSC Young Boys": {"api_id": "565", "country": "Switzerland"},
    "FC Zurich": {"api_id": "783", "country": "Switzerland"},
    "FC Lausanne-Sport": {"api_id": "1014", "country": "Switzerland"},
    "FC St. Gallen": {"api_id": "1011", "country": "Switzerland"},
    "FC Sion": {"api_id": "630", "country": "Switzerland"},
    "Yverdon-Sport FC": {"api_id": "6653", "country": "Switzerland"},
    "Grasshopper-Club": {"api_id": "1013", "country": "Switzerland"},
    "FC Winterthur": {"api_id": "2180", "country": "Switzerland"},

    # Denmark Teams (Denmark)
    "FC Midtjylland": {"api_id": "397", "country": "Denmark"},
    "FC Copenhagen": {"api_id": "400", "country": "Denmark"},
    "AGF": {"api_id": "14243", "country": "Denmark"},
    "Randers FC": {"api_id": "799", "country": "Denmark"},
    "FC Nordsjaelland": {"api_id": "398", "country": "Denmark"},
    "Brondby": {"api_id": "407", "country": "Denmark"},
    "Silkeborg": {"api_id": "2073", "country": "Denmark"},
    "Viborg": {"api_id": "2070", "country": "Denmark"},
    "Aalborg": {"api_id": "402", "country": "Denmark"},
    "Lyngby": {"api_id": "625", "country": "Denmark"},
    "SonderjyskE": {"api_id": "396", "country": "Denmark"},
    "Vejle": {"api_id": "395", "country": "Denmark"},

    # Ukraine Teams (Ukraine)
    "Dinamo Kiev": {"api_id": "572", "country": "Ukraine"},
    "FC Oleksandriya": {"api_id": "3619", "country": "Ukraine"},
    "Shakhter Donetsk": {"api_id": "550", "country": "Ukraine"},
    "Polissya Zhytomyr": {"api_id": "13258", "country": "Ukraine"},
    "Kryvbas Kryvyi Rih": {"api_id": "13248", "country": "Ukraine"},
    "Zarya Lugansk": {"api_id": "599", "country": "Ukraine"},
    "Karpaty Lviv": {"api_id": "3617", "country": "Ukraine"},
    "Veres": {"api_id": "6501", "country": "Ukraine"},
    "Rukh Lviv": {"api_id": "3632", "country": "Ukraine"},
    "Cherkasi": {"api_id": "17161", "country": "Ukraine"},
    "Livyi Bereg": {"api_id": "17162", "country": "Ukraine"},
    "Vorskla Poltava": {"api_id": "1121", "country": "Ukraine"},
    "Kolos Kovalivka": {"api_id": "3627", "country": "Ukraine"},
    "Obolon-Brovar Kiev": {"api_id": "3630", "country": "Ukraine"},
    "Chernomorets Odessa": {"api_id": "3615", "country": "Ukraine"},
    "Ingulets Petrove": {"api_id": "3625", "country": "Ukraine"},

    # Czech Republic Teams (Czech Republic)
    "Slavia Praha": {"api_id": "560", "country": "Czech Republic"},
    "Sparta Praha": {"api_id": "628", "country": "Czech Republic"},
    "Viktoria Plzen": {"api_id": "567", "country": "Czech Republic"},
    "Banik Ostrava": {"api_id": "3713", "country": "Czech Republic"},
    "FK Jablonec": {"api_id": "1122", "country": "Czech Republic"},
    "Sigma Olomouc": {"api_id": "2250", "country": "Czech Republic"},
    "Mlada Boleslav": {"api_id": "640", "country": "Czech Republic"},
    "Slovan Liberec": {"api_id": "782", "country": "Czech Republic"},
    "Bohemians 1905": {"api_id": "3714", "country": "Czech Republic"},
    "Hradec Kralove": {"api_id": "3723", "country": "Czech Republic"},
    "Teplice": {"api_id": "3720", "country": "Czech Republic"},
    "Karvina": {"api_id": "3716", "country": "Czech Republic"},
    "Slovacko": {"api_id": "3719", "country": "Czech Republic"},
    "Dukla Praha": {"api_id": "3715", "country": "Czech Republic"},
    "Pardubice": {"api_id": "3724", "country": "Czech Republic"},
    "Dynamo Ceske Budejovice": {"api_id": "3736", "country": "Czech Republic"},

    # Greece Teams (Greece)
    "Olympiakos Piraeus": {"api_id": "553", "country": "Greece"},
    "AEK Athens": {"api_id": "575", "country": "Greece"},
    "Panathinaikos": {"api_id": "617", "country": "Greece"},
    "PAOK": {"api_id": "619", "country": "Greece"},
    "Aris Thessalonikis": {"api_id": "1123", "country": "Greece"},
    "OFI": {"api_id": "1124", "country": "Greece"},
    "Atromitos Athinon": {"api_id": "12260", "country": "Greece"},
    "Asteras Tripolis": {"api_id": "955", "country": "Greece"},
    "Panaitolikos": {"api_id": "949", "country": "Greece"},
    "Levadiakos": {"api_id": "957", "country": "Greece"},
    "Panserraikos": {"api_id": "2099", "country": "Greece"},
    "Volos NPS": {"api_id": "2110", "country": "Greece"},
    "Kallithea": {"api_id": "2095", "country": "Greece"},
    "Lamia": {"api_id": "956", "country": "Greece"},

    # Poland Teams (Poland)
    "Rakow Czestochowa": {"api_id": "3491", "country": "Poland"},
    "Jagiellonia": {"api_id": "336", "country": "Poland"},
    "Lech Poznan": {"api_id": "347", "country": "Poland"},
    "Pogon Szczecin": {"api_id": "348", "country": "Poland"},
    "Legia Warszawa": {"api_id": "339", "country": "Poland"},
    "Gornik Zabrze": {"api_id": "340", "country": "Poland"},
    "Cracovia Krakow": {"api_id": "350", "country": "Poland"},
    "Motor Lublin": {"api_id": "14562", "country": "Poland"},
    "GKS Katowice": {"api_id": "3484", "country": "Poland"},
    "Piast Gliwice": {"api_id": "349", "country": "Poland"},
    "Korona Kielce": {"api_id": "346", "country": "Poland"},
    "Radomiak Radom": {"api_id": "4248", "country": "Poland"},
    "Widzew Lodz": {"api_id": "6962", "country": "Poland"},
    "Puszcza Niepolomice": {"api_id": "3490", "country": "Poland"},
    "Stal Mielec": {"api_id": "3493", "country": "Poland"},
    "Zaglebie Lubin": {"api_id": "345", "country": "Poland"},
    "Lechia Gdansk": {"api_id": "343", "country": "Poland"},
    "Slask Wroclaw": {"api_id": "337", "country": "Poland"},

    # Croatia Teams (Croatia)
    "HNK Rijeka": {"api_id": "561", "country": "Croatia"},
    "HNK Hajduk Split": {"api_id": "608", "country": "Croatia"},
    "NK Dinamo Zagreb": {"api_id": "620", "country": "Croatia"},
    "NK Varazdin": {"api_id": "1483", "country": "Croatia"},
    "NK Slaven Belupo": {"api_id": "1018", "country": "Croatia"},
    "NK Osijek": {"api_id": "616", "country": "Croatia"},
    "NK Lokomotiva Zagreb": {"api_id": "1017", "country": "Croatia"},
    "Istra 1961": {"api_id": "1016", "country": "Croatia"},
    "HNK Gorica": {"api_id": "1068", "country": "Croatia"},
    "Sibenik": {"api_id": "1475", "country": "Croatia"},

    # Serbia Teams (Serbia)
    "Crvena Zvezda": {"api_id": "598", "country": "Serbia"},
    "FK Partizan": {"api_id": "573", "country": "Serbia"},
    "Radnicki 1923": {"api_id": "2644", "country": "Serbia"},
    "OFK Beograd": {"api_id": "2633", "country": "Serbia"},
    "Mladost Lucani": {"api_id": "699", "country": "Serbia"},
    "Vojvodina": {"api_id": "702", "country": "Serbia"},
    "Novi Pazar": {"api_id": "2643", "country": "Serbia"},
    "TSC Backa Topola": {"api_id": "2646", "country": "Serbia"},
    "Cukaricki": {"api_id": "2656", "country": "Serbia"},
    "Zeleznicar Pancevo": {"api_id": "12360", "country": "Serbia"},
    "FK IMT Beograd": {"api_id": "12316", "country": "Serbia"},
    "Spartak Subotica": {"api_id": "10903", "country": "Serbia"},
    "Napredak": {"api_id": "2655", "country": "Serbia"},
    "Radnicki Nis": {"api_id": "2254", "country": "Serbia"},
    "Tekstilac Odzaci": {"api_id": "17438", "country": "Serbia"},
    "Jedinstvo Ub": {"api_id": "12319", "country": "Serbia"},

    # Cyprus Teams (Cyprus)
    "Aris": {"api_id": "114", "country": "Cyprus"},
    "Pafos FC": {"api_id": "3403", "country": "Cyprus"},
    "A. E. Kition Larnaca": {"api_id": "614", "country": "Cyprus"},
    "Omonia": {"api_id": "3402", "country": "Cyprus"},
    "Apoel": {"api_id": "2247", "country": "Cyprus"},
    "Apollon Limassol": {"api_id": "602", "country": "Cyprus"},
    "Anorthosis": {"api_id": "2269", "country": "Cyprus"},
    "Ethnikos Achnas": {"api_id": "3412", "country": "Cyprus"},
    "Baskent Y. Ankara": {"api_id": "3396", "country": "Cyprus"},
    "Karmiotissa Polemidion": {"api_id": "3413", "country": "Cyprus"},
    "Omonia Aradippou": {"api_id": "3416", "country": "Cyprus"},
    "E.N. Paralimniou": {"api_id": "3399", "country": "Cyprus"},
    "Nea Salamis": {"api_id": "3401", "country": "Cyprus"},
    "Omonoia 29m": {"api_id": "14126", "country": "Cyprus"},

    # Romania Teams (Romania)
    "CFR 1907 Cluj": {"api_id": "2246", "country": "Romania"},
    "FCSB": {"api_id": "559", "country": "Romania"},
    "CS Universitatea Craiova": {"api_id": "632", "country": "Romania"},
    "Universitatea Cluj": {"api_id": "2599", "country": "Romania"},
    "Dinamo Bucuresti": {"api_id": "635", "country": "Romania"},
    "Rapid Bucuresti": {"api_id": "6231", "country": "Romania"},
    "AFC Hermannstadt": {"api_id": "2579", "country": "Romania"},
    "Sepsi OSK": {"api_id": "2585", "country": "Romania"},
    "Petrolul Ploiesti": {"api_id": "2598", "country": "Romania"},
    "UTA Arad": {"api_id": "2589", "country": "Romania"},
    "Farul Constanta": {"api_id": "2596", "country": "Romania"},
    "FC Botosani": {"api_id": "2581", "country": "Romania"},
    "Poli Iasi": {"api_id": "2583", "country": "Romania"},
    "Otelul Galati": {"api_id": "6886", "country": "Romania"},
    "Unirea 2004 Slobozia": {"api_id": "6916", "country": "Romania"},
    "Gloria Buzau": {"api_id": "6232", "country": "Romania"},

    # Hungary Teams (Hungary)
    "Puskas Academy": {"api_id": "2391", "country": "Hungary"},
    "Ferencvarosi TC": {"api_id": "651", "country": "Hungary"},
    "Paks": {"api_id": "2390", "country": "Hungary"},
    "MTK Budapest": {"api_id": "2396", "country": "Hungary"},
    "Diosgyori VTK": {"api_id": "2393", "country": "Hungary"},
    "Gyori Eto FC": {"api_id": "2402", "country": "Hungary"},
    "Ujpest": {"api_id": "2255", "country": "Hungary"},
    "MOL Fehervar FC": {"api_id": "610", "country": "Hungary"},
    "Zalaegerszegi TE": {"api_id": "2414", "country": "Hungary"},
    "Nyiregyhaza": {"api_id": "2403", "country": "Hungary"},
    "Debreceni VSC": {"api_id": "2392", "country": "Hungary"},
    "Kecskemeti TE": {"api_id": "5111", "country": "Hungary"},
}