# utils/predict.py
import pandas as pd
import numpy as np
from typing import List, Dict, Set
import warnings

# Import the enhanced config class
from config import PredictionConfig

def format_predictions(
    base_probabilities: Dict[str, np.ndarray],
    match_info: pd.DataFrame,
    config: PredictionConfig, # Use the imported, enhanced config class
    model_prefix: str # Add model_prefix (e.g., "poisson", "random_forest")
) -> pd.DataFrame:
    """
    Generates ranked single and dual outcome predictions based on PredictionConfig,
    using accurately calculated dual probabilities (via scoreline summation).

    Args:
        base_probabilities: Dict output from model.predict_proba(). MUST contain keys
                            for all single and dual outcomes specified in config,
                            prefixed by the model name.
        match_info: DataFrame with match identifiers. *Must contain unique MatchIDs*.
        config: PredictionConfig settings object controlling output.
        model_prefix: The prefix used by the model for its probability keys (e.g., "poisson_").

    Returns:
        DataFrame with columns ['MatchID', 'HomeTeam', 'AwayTeam', 'Rank', 'Outcome', 'Probability']
    """
    # --- Input Assertions ---
    assert isinstance(match_info, pd.DataFrame), "match_info must be a DataFrame."
    required_match_cols = set(config.required_match_info_cols)
    assert required_match_cols.issubset(match_info.columns), \
        f"Missing required columns in match_info based on config: {required_match_cols - set(match_info.columns)}"

    match_id_col = config.required_match_info_cols[0] # Assumes MatchID is the first column
    assert not match_info[match_id_col].duplicated().any(), \
        f"Duplicate MatchIDs found in match_info DataFrame using column '{match_id_col}'. Ensure input data contains unique matches."
    
    assert isinstance(model_prefix, str) and model_prefix.endswith('_'), "model_prefix must be a string ending with '_'"

    # Determine the set of all probability keys required based on the config (unprefixed)
    allowed_unprefixed_keys_from_config: Set[str] = config.get_allowed_prediction_keys()

    # Check if all required keys (when prefixed) are present in the input dictionary
    missing_prefixed_keys = {f"{model_prefix}{unprefixed_key}" for unprefixed_key in allowed_unprefixed_keys_from_config} - set(base_probabilities.keys())
    assert not missing_prefixed_keys, \
        f"Missing required (prefixed) probability keys in base_probabilities: {missing_prefixed_keys}. " \
        f"Ensure the model's predict_proba returns all keys selected by PredictionConfig, prefixed with '{model_prefix}'."

    n_matches = len(match_info)
    # Verify types and lengths of the required arrays (checking prefixed keys)
    assert all(
        isinstance(v, np.ndarray) and len(v) == n_matches
        for k, v in base_probabilities.items()
        if k in {f"{model_prefix}{unprefixed_key}" for unprefixed_key in allowed_unprefixed_keys_from_config}
    ), f"Probability arrays for selected keys (prefixed with '{model_prefix}') must be numpy arrays of length {n_matches}."

    all_final_predictions = []
    print(f"Generating top {config.n_top_predictions} predictions per match for {n_matches} matches using scoreline-summed probabilities...")

    # --- Outcome Name Mapping (MUST BE EXPANDED TO BE COMPREHENSIVE) ---
    # This map needs to cover ALL keys potentially generated by calculate_poisson_outcome_probs
    # and selected by config.get_allowed_prediction_keys()
    outcome_name_map = {
        # Singles
        'prob_H': "[Home Win]", 'prob_D': "[Draw]", 'prob_A': "[Away Win]",
        'prob_1X': "[Home Win or Draw]", 'prob_X2': "[Away Win or Draw]", 'prob_12': "[Home Win or Away Win]",
        'prob_O15': "[Over 1.5]", 'prob_U15': "[Under 1.5]",
        'prob_O25': "[Over 2.5]", 'prob_U25': "[Under 2.5]",
        'prob_O35': "[Over 3.5]", 'prob_U35': "[Under 3.5]",
        'prob_BTTS_Y': "[BTTS Yes]", 'prob_BTTS_N': "[BTTS No]",
        'prob_goals_0_1': "[Goals 0-1]",
        'prob_goals_2_3': "[Goals 2-3]",
        'prob_goals_2_4': "[Goals 2-4]",
        'prob_goals_3_plus': "[Goals 3+]", # This is prob_O25

        # --- Match Result + Goals (ALL LINES) ---
        'prob_H_and_O15': '[Home Win + Over 1.5]', 'prob_D_and_O15': '[Draw + Over 1.5]', 'prob_A_and_O15': '[Away Win + Over 1.5]',
        'prob_H_and_U15': '[Home Win + Under 1.5]', 'prob_D_and_U15': '[Draw + Under 1.5]', 'prob_A_and_U15': '[Away Win + Under 1.5]',
        'prob_H_and_O25': '[Home Win + Over 2.5]', 'prob_D_and_O25': '[Draw + Over 2.5]', 'prob_A_and_O25': '[Away Win + Over 2.5]',
        'prob_H_and_U25': '[Home Win + Under 2.5]', 'prob_D_and_U25': '[Draw + Under 2.5]', 'prob_A_and_U25': '[Away Win + Under 2.5]',
        'prob_H_and_O35': '[Home Win + Over 3.5]', 'prob_D_and_O35': '[Draw + Over 3.5]', 'prob_A_and_O35': '[Away Win + Over 3.5]',
        'prob_H_and_U35': '[Home Win + Under 3.5]', 'prob_D_and_U35': '[Draw + Under 3.5]', 'prob_A_and_U35': '[Away Win + Under 3.5]',
        'prob_H_and_O45': '[Home Win + Over 4.5]', 'prob_D_and_O45': '[Draw + Over 4.5]', 'prob_A_and_O45': '[Away Win + Over 4.5]',
        'prob_H_and_U45': '[Home Win + Under 4.5]', 'prob_D_and_U45': '[Draw + Under 4.5]', 'prob_A_and_U45': '[Away Win + Under 4.5]',

        # --- Double Chance + Goals (ALL LINES) ---
        'prob_1X_and_O15': '[Home Win or Draw + Over 1.5]', 'prob_12_and_O15': '[Home Win or Away Win + Over 1.5]', 'prob_X2_and_O15': '[Draw or Away Win + Over 1.5]',
        'prob_1X_and_U15': '[Home Win or Draw + Under 1.5]', 'prob_12_and_U15': '[Home Win or Away Win + Under 1.5]', 'prob_X2_and_U15': '[Draw or Away Win + Under 1.5]',
        'prob_1X_and_O25': '[Home Win or Draw + Over 2.5]', 'prob_12_and_O25': '[Home Win or Away Win + Over 2.5]', 'prob_X2_and_O25': '[Draw or Away Win + Over 2.5]',
        'prob_1X_and_U25': '[Home Win or Draw + Under 2.5]', 'prob_12_and_U25': '[Home Win or Away Win + Under 2.5]', 'prob_X2_and_U25': '[Draw or Away Win + Under 2.5]',
        'prob_1X_and_O35': '[Home Win or Draw + Over 3.5]', 'prob_12_and_O35': '[Home Win or Away Win + Over 3.5]', 'prob_X2_and_O35': '[Draw or Away Win + Over 3.5]',
        'prob_1X_and_U35': '[Home Win or Draw + Under 3.5]', 'prob_12_and_U35': '[Home Win or Away Win + Under 3.5]', 'prob_X2_and_U35': '[Draw or Away Win + Under 3.5]',
        'prob_1X_and_O45': '[Home Win or Draw + Over 4.5]', 'prob_12_and_O45': '[Home Win or Away Win + Over 4.5]', 'prob_X2_and_O45': '[Draw or Away Win + Over 4.5]',
        'prob_1X_and_U45': '[Home Win or Draw + Under 4.5]', 'prob_12_and_U45': '[Home Win or Away Win + Under 4.5]', 'prob_X2_and_U45': '[Draw or Away Win + Under 4.5]',

        # --- Match Result + BTTS ---
        'prob_H_and_BTTS_Y': '[Home Win + BTTS Yes]', 'prob_D_and_BTTS_Y': '[Draw + BTTS Yes]', 'prob_A_and_BTTS_Y': '[Away Win + BTTS Yes]',
        'prob_H_and_BTTS_N': '[Home Win + BTTS No]', 'prob_D_and_BTTS_N': '[Draw + BTTS No]', 'prob_A_and_BTTS_N': '[Away Win + BTTS No]',
        'prob_home_or_away_and_BTTS_Y': '[Home or Away Win + BTTS Yes]', 'prob_home_or_away_and_BTTS_N': '[Home or Away Win + BTTS No]',
        'prob_home_or_draw_and_BTTS_Y': '[Home or Draw Win + BTTS Yes]', 'prob_home_or_draw_and_BTTS_N': '[Home or Draw Win + BTTS No]',
        'prob_away_or_draw_and_BTTS_Y': '[Away or Draw Win + BTTS Yes]', 'prob_away_or_draw_and_BTTS_N': '[Away or Draw Win + BTTS No]',


        # --- Double Chance + BTTS ---
        'prob_1X_and_BTTS_Y': '[Home Win or Draw + BTTS Yes]', 'prob_12_and_BTTS_Y': '[Home Win or Away Win + BTTS Yes]', 'prob_X2_and_BTTS_Y': '[Draw or Away Win + BTTS Yes]',
        'prob_1X_and_BTTS_N': '[Home Win or Draw + BTTS No]', 'prob_12_and_BTTS_N': '[Home Win or Away Win + BTTS No]', 'prob_X2_and_BTTS_N': '[Draw or Away Win + BTTS No]',
        
        # --- Goals + BTTS (ALL LINES) ---
        'prob_O25_and_BTTS_Y': '[Over 2.5 + BTTS Yes]', 'prob_O25_and_BTTS_N': '[Over 2.5 + BTTS No]',
        'prob_O35_and_BTTS_Y': '[Over 3.5 + BTTS Yes]', 'prob_O35_and_BTTS_N': '[Over 3.5 + BTTS No]',
    }

    unmapped_keys = allowed_unprefixed_keys_from_config - set(outcome_name_map.keys())
    # Add a check for keys that are impossible combinations (like U0.5 and BTTS_Y)
    # if they are somehow generated by config.get_allowed_prediction_keys()
    # For now, the map should cover all practically selectable keys.
    if unmapped_keys:
        warnings.warn(
            f"outcome_name_map might be missing mappings for some selected keys "
            f"or config selected impossible combinations: {unmapped_keys}. "
            f"Ensure CORE_PREDICTION_KEYS and PredictionConfig align with outcome_name_map "
            f"and poisson_model.py's capabilities."
        )

    # --- Iterate through each match ---
    for i in range(n_matches):
        match_id = match_info.iloc[i][config.required_match_info_cols[0]]
        home_team = match_info.iloc[i][config.required_match_info_cols[1]]
        away_team = match_info.iloc[i][config.required_match_info_cols[2]]

        # Collect potential predictions for this match {OutcomeName: Probability}
        # Directly use the probabilities from base_probabilities based on config
        items_to_sort = []
        for unprefixed_prob_key in allowed_unprefixed_keys_from_config:
            prefixed_key = f"{model_prefix}{unprefixed_prob_key}" # Construct the prefixed key

            if prefixed_key in base_probabilities:
                prob = base_probabilities[prefixed_key][i]
                # Use unprefixed key for the map, as map keys are unprefixed
                outcome_name = outcome_name_map.get(unprefixed_prob_key) 

                if outcome_name is None:
                    warnings.warn(f"MatchID {match_id}: No outcome name mapping for unprefixed key '{unprefixed_prob_key}'. Skipping this outcome.")
                    continue

                # Check threshold and validity
                if isinstance(prob, (float, np.floating)) and np.isfinite(prob) and prob >= config.min_probability_threshold:
                    items_to_sort.append((outcome_name, prob))
                elif not np.isfinite(prob):
                     warnings.warn(f"MatchID {match_id}: Skipping outcome '{outcome_name}' (from key '{prefixed_key}') due to non-finite probability ({prob}).")
            # else: # This case should be caught by the assertion at the beginning
            #    warnings.warn(f"Prefixed key '{prefixed_key}' (derived from config key '{unprefixed_prob_key}') not found in base_probabilities for MatchID {match_id}.")

        # --- Sort predictions by probability ---
        sorted_preds = sorted(items_to_sort, key=lambda item: item[1], reverse=True)

        # --- Take top N predictions ---
        top_preds = sorted_preds[:config.n_top_predictions]

        # --- Add match info and rank to the final list ---
        for rank, (outcome, prob) in enumerate(top_preds, 1):
            all_final_predictions.append({
                "MatchID": match_id,
                "HomeTeam": home_team,
                "AwayTeam": away_team,
                "Rank": rank,
                "Outcome": outcome,
                "Probability": prob
            })

    # --- Create Final DataFrame ---
    output_df = pd.DataFrame(all_final_predictions)

    # --- Final Assertions on Output DataFrame Structure ---
    if not output_df.empty:
        # Check probability range
        assert output_df['Probability'].between(0, 1).all(), "Final probabilities are outside [0, 1]."

        # Check ranks are consecutive and start from 1 per match
        grouped_ranks = output_df.groupby('MatchID')['Rank']
        min_ranks = grouped_ranks.min()
        max_ranks = grouped_ranks.max()
        count_ranks = grouped_ranks.count()

        failed_min_rank = min_ranks[min_ranks != 1]
        assert failed_min_rank.empty, \
            f"Rank does not start at 1 for all matches with predictions. Problematic MatchIDs: {failed_min_rank.index.tolist()}"

        # Check max rank equals the count of predictions for that match
        # Allow max_rank to be less than config.n_top_predictions if fewer than N outcomes met the threshold
        failed_max_rank_count = max_ranks[max_ranks != count_ranks]
        assert failed_max_rank_count.empty, \
            f"Max rank ({max_ranks[failed_max_rank_count.index].tolist()}) does not equal count ({count_ranks[failed_max_rank_count.index].tolist()}) of predictions per match. Problematic MatchIDs: {failed_max_rank_count.index.tolist()}"

        # Check that the maximum rank doesn't exceed the configured limit
        failed_max_rank_limit = max_ranks[max_ranks > config.n_top_predictions]
        assert failed_max_rank_limit.empty, \
            f"Max rank exceeds n_top_predictions ({config.n_top_predictions}) for some matches. Problematic MatchIDs: {failed_max_rank_limit.index.tolist()}"
    else:
        print("No predictions met the threshold criteria; output DataFrame is empty.")

    print(f"Formatted top predictions per match successfully using accurate dual probabilities.")
    return output_df