# utils/predict.py
import pandas as pd
import numpy as np
from typing import List, Dict, Set
import warnings

# Import the enhanced config class
from models.utils.config import PredictionConfig

def format_predictions(
    base_probabilities: Dict[str, np.ndarray],
    match_info: pd.DataFrame,
    config: PredictionConfig # Use the imported, enhanced config class
) -> pd.DataFrame:
    """
    Generates ranked single and dual outcome predictions based on PredictionConfig,
    using accurately calculated dual probabilities (via scoreline summation).

    Args:
        base_probabilities: Dict output from model.predict_proba(). MUST contain keys
                            for all single and dual outcomes specified in config.
        match_info: DataFrame with match identifiers. *Must contain unique MatchIDs*.
        config: PredictionConfig settings object controlling output.

    Returns:
        DataFrame with columns ['MatchID', 'HomeTeam', 'AwayTeam', 'Rank', 'Outcome', 'Probability']
    """
    # --- Input Assertions ---
    assert isinstance(match_info, pd.DataFrame), "match_info must be a DataFrame."
    required_match_cols = set(config.required_match_info_cols)
    assert required_match_cols.issubset(match_info.columns), \
        f"Missing required columns in match_info based on config: {required_match_cols - set(match_info.columns)}"

    match_id_col = config.required_match_info_cols[0] # Assumes MatchID is the first column
    assert not match_info[match_id_col].duplicated().any(), \
        f"Duplicate MatchIDs found in match_info DataFrame using column '{match_id_col}'. Ensure input data contains unique matches."

    # Determine the set of all probability keys required based on the config
    allowed_keys_from_config: Set[str] = config.get_allowed_prediction_keys()

    # Check if all required keys are present in the input dictionary
    missing_keys = allowed_keys_from_config - set(base_probabilities.keys())
    assert not missing_keys, \
        f"Missing required probability keys in base_probabilities based on PredictionConfig: {missing_keys}. " \
        f"Ensure the model's predict_proba returns all keys listed in config's include_* lists."

    n_matches = len(match_info)
    # Verify types and lengths of the required arrays
    assert all(isinstance(v, np.ndarray) and len(v) == n_matches for k, v in base_probabilities.items() if k in allowed_keys_from_config), \
        f"Probability arrays listed in config must be numpy arrays of length {n_matches}."

    all_final_predictions = []
    print(f"Generating top {config.n_top_predictions} predictions per match for {n_matches} matches using scoreline-summed probabilities...")

    # --- Outcome Name Mapping (Expanded for Duals) ---
    # This map needs to cover ALL keys potentially generated by calculate_poisson_outcome_probs
    # and selected by config.get_allowed_prediction_keys()
    outcome_name_map = {
        # Singles
        'prob_H': "[Home Win]", 'prob_D': "[Draw]", 'prob_A': "[Away Win]",
        'prob_1X': "[Home Win or Draw]", 'prob_X2': "[Away Win or Draw]", 'prob_12': "[Home Win or Away Win]",
        'prob_O05': "[Over 0.5]", 'prob_U05': "[Under 0.5]",
        'prob_O15': "[Over 1.5]", 'prob_U15': "[Under 1.5]",
        'prob_O25': "[Over 2.5]", 'prob_U25': "[Under 2.5]",
        'prob_O35': "[Over 3.5]", 'prob_U35': "[Under 3.5]",
        'prob_O45': "[Over 4.5]", 'prob_U45': "[Under 4.5]",
        'prob_BTTS_Y': "[BTTS Yes]", 'prob_BTTS_N': "[BTTS No]",
        'prob_goals_0_1': "[Goals 0-1]",
        'prob_goals_2_3': "[Goals 2-3]",
        'prob_goals_2_4': "[Goals 2-4]",
        'prob_goals_3_plus': "[Goals 3+]",
        # Duals: 1X2 & O/U 2.5
        'prob_H_and_O25': '[Home Win + Over 2.5]', 'prob_D_and_O25': '[Draw + Over 2.5]', 'prob_A_and_O25': '[Away Win + Over 2.5]',
        'prob_H_and_U25': '[Home Win + Under 2.5]', 'prob_D_and_U25': '[Draw + Under 2.5]', 'prob_A_and_U25': '[Away Win + Under 2.5]',
        # Duals: Double Chance & O/U 2.5
        'prob_1X_and_O25': '[Home Win or Draw + Over 2.5]', 'prob_12_and_O25': '[Home Win or Away Win + Over 2.5]', 'prob_X2_and_O25': '[Draw or Away Win + Over 2.5]',
        'prob_1X_and_U25': '[Home Win or Draw + Under 2.5]', 'prob_12_and_U25': '[Home Win or Away Win + Under 2.5]', 'prob_X2_and_U25': '[Draw or Away Win + Under 2.5]',
        # Duals: 1X2 & BTTS
        'prob_H_and_BTTS_Y': '[Home Win + BTTS Yes]', 'prob_D_and_BTTS_Y': '[Draw + BTTS Yes]', 'prob_A_and_BTTS_Y': '[Away Win + BTTS Yes]',
        'prob_H_and_BTTS_N': '[Home Win + BTTS No]', 'prob_D_and_BTTS_N': '[Draw + BTTS No]', 'prob_A_and_BTTS_N': '[Away Win + BTTS No]',
        # Duals: Double Chance & BTTS
        'prob_1X_and_BTTS_Y': '[Home Win or Draw + BTTS Yes]', 'prob_12_and_BTTS_Y': '[Home Win or Away Win + BTTS Yes]', 'prob_X2_and_BTTS_Y': '[Draw or Away Win + BTTS Yes]',
        'prob_1X_and_BTTS_N': '[Home Win or Draw + BTTS No]', 'prob_12_and_BTTS_N': '[Home Win or Away Win + BTTS No]', 'prob_X2_and_BTTS_N': '[Draw or Away Win + BTTS No]',
        # Duals: O/U 2.5 & BTTS
        'prob_O25_and_BTTS_Y': '[Over 2.5 + BTTS Yes]', 'prob_O25_and_BTTS_N': '[Over 2.5 + BTTS No]',
        'prob_U25_and_BTTS_Y': '[Under 2.5 + BTTS Yes]', 'prob_U25_and_BTTS_N': '[Under 2.5 + BTTS No]',
         # Add other potential duals if calculated by poisson_model.py, e.g., involving O/U 1.5, 3.5 etc.
    }

    # Assert all keys selected by the config are mapped
    unmapped_keys = allowed_keys_from_config - set(outcome_name_map.keys())
    assert not unmapped_keys, \
        f"outcome_name_map is missing mappings for probability keys selected by PredictionConfig: {unmapped_keys}"

    # --- Iterate through each match ---
    for i in range(n_matches):
        match_id = match_info.iloc[i][config.required_match_info_cols[0]]
        home_team = match_info.iloc[i][config.required_match_info_cols[1]]
        away_team = match_info.iloc[i][config.required_match_info_cols[2]]

        # Collect potential predictions for this match {OutcomeName: Probability}
        # Directly use the probabilities from base_probabilities based on config
        items_to_sort = []
        for prob_key in allowed_keys_from_config:
            # Check if the key exists (already asserted above, but safe practice)
            if prob_key in base_probabilities:
                prob = base_probabilities[prob_key][i]
                outcome_name = outcome_name_map[prob_key] # Use the mapped name

                # Check threshold and validity
                if isinstance(prob, (float, np.floating)) and np.isfinite(prob) and prob >= config.min_probability_threshold:
                    items_to_sort.append((outcome_name, prob))
                elif not np.isfinite(prob):
                     warnings.warn(f"MatchID {match_id}: Skipping outcome '{outcome_name}' (from key '{prob_key}') due to non-finite probability ({prob}).")


        # --- Sort predictions by probability ---
        sorted_preds = sorted(items_to_sort, key=lambda item: item[1], reverse=True)

        # --- Take top N predictions ---
        top_preds = sorted_preds[:config.n_top_predictions]

        # --- Add match info and rank to the final list ---
        for rank, (outcome, prob) in enumerate(top_preds, 1):
            all_final_predictions.append({
                "MatchID": match_id,
                "HomeTeam": home_team,
                "AwayTeam": away_team,
                "Rank": rank,
                "Outcome": outcome,
                "Probability": prob
            })

    # --- Create Final DataFrame ---
    output_df = pd.DataFrame(all_final_predictions)

    # --- Final Assertions on Output DataFrame Structure ---
    if not output_df.empty:
        # Check probability range
        assert output_df['Probability'].between(0, 1).all(), "Final probabilities are outside [0, 1]."

        # Check ranks are consecutive and start from 1 per match
        grouped_ranks = output_df.groupby('MatchID')['Rank']
        min_ranks = grouped_ranks.min()
        max_ranks = grouped_ranks.max()
        count_ranks = grouped_ranks.count()

        failed_min_rank = min_ranks[min_ranks != 1]
        assert failed_min_rank.empty, \
            f"Rank does not start at 1 for all matches with predictions. Problematic MatchIDs: {failed_min_rank.index.tolist()}"

        # Check max rank equals the count of predictions for that match
        # Allow max_rank to be less than config.n_top_predictions if fewer than N outcomes met the threshold
        failed_max_rank_count = max_ranks[max_ranks != count_ranks]
        assert failed_max_rank_count.empty, \
            f"Max rank ({max_ranks[failed_max_rank_count.index].tolist()}) does not equal count ({count_ranks[failed_max_rank_count.index].tolist()}) of predictions per match. Problematic MatchIDs: {failed_max_rank_count.index.tolist()}"

        # Check that the maximum rank doesn't exceed the configured limit
        failed_max_rank_limit = max_ranks[max_ranks > config.n_top_predictions]
        assert failed_max_rank_limit.empty, \
            f"Max rank exceeds n_top_predictions ({config.n_top_predictions}) for some matches. Problematic MatchIDs: {failed_max_rank_limit.index.tolist()}"
    else:
        print("No predictions met the threshold criteria; output DataFrame is empty.")


    print(f"Formatted top predictions per match successfully using accurate dual probabilities.")
    return output_df